//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// RemoteGraph.rc で使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDP_SOCKETS_INIT_FAILED         102
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  116
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_RemoteGraphTYPE             130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               152
#define IDR_WINDOWS_MENU                153
#define ID_PROPERTIES1                  154
#define ID_PROPERTIES2                  155
#define ID_EXPAND_ALL                   156
#define IDS_FILE_VIEW                   157
#define IDS_CLASS_VIEW                  158
#define IDS_OUTPUT_WND                  159
#define IDS_PROPERTIES_WND              160
#define IDI_FILE_VIEW                   161
#define IDS_FILE_VIEW2                  161
#define IDS_STATUS_VIEW                 161
#define IDS_LIMIT_WND                   162
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDI_LIMIT_WND_HC                169
#define IDB_EXPLORER_24                 170
#define IDI_LIMIT_WND                   170
#define IDR_SORT                        171
#define IDI_OUTPUT_WND_HC1              171
#define IDI_STATUS_VIEW_HC              171
#define IDB_SORT_24                     172
#define IDI_STATUS_VIEW                 172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define IDR_LIMIT_POPUP                 201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDS_DATA_TAB_1                  308
#define IDS_DATA_TAB_2                  309
#define IDS_DATA_TAB_3                  310
#define IDS_DATA_TAB_4                  311
#define IDS_DATA_TAB_5                  312
#define IDS_DATA_TAB_6                  313
#define IDS_DATA_TAB_7                  314
#define IDS_DATA_TAB_8                  315
#define IDD_DIALOG_ADDDATA              316
#define IDD_STARTDATE                   317
#define IDD_STARTDATEDLG                318
#define ID_VIEW_STATUSVIEW              319
#define ID_VIEW_LIMITWND                320
#define IDD_DIALOG_WAIT                 433
#define IDC_COMBO_STATION               1000
#define IDC_COMBO_EQUIPMENT             1001
#define IDC_LIST1                       1002
#define IDC_LIST2                       1003
#define IDC_BUTTON_ADD                  1004
#define IDC_BUTTON_DEL                  1005
#define IDC_BUTTON_UP                   1006
#define IDC_BUTTON_UP2                  1007
#define IDC_DATETIMEPICKER1             1008
#define IDC_BUTTON_DOWN                 1009
#define IDC_MONTHCALENDAR1              1010
#define IDC_DATETIMEPICKER2             1011
#define IDC_CHECK_AUTO_ASSIGN           1012
#define IDC_PROGRESS1                   1013
#define IDC_PROGRESS_WAIT               1013
#define IDC_BUTTON_ABORT                2499
#define IDC_STATIC_MESSAGE              3005
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_EDIT_STATION                 32771
#define ID_BUTTON_ONLINE                32772
#define ID_CHECK_GRAPH1                 32773
#define ID_CHECK_GRAPH2                 32774
#define ID_CHECK_GRAPH3                 32775
#define ID_CHECK_GRAPH4                 32776
#define ID_CHECK_GRAPH5                 32777
#define ID_CHECK_GRAPH6                 32778
#define ID_CHECK_GRAPH7                 32779
#define ID_CHECK_GRAPH8                 32780
#define ID_CHECK_GRAPH9                 32780
#define ID_VIEW_PROPERTIES              32781
#define ID_BUTTON_ONLINE_STOP           32782
#define ID_VIEW_DATALIST                32783
#define ID_VIEW_OUTPUT                  32784
#define ID_BTN_GRAPH_CLEAR1             32785
#define ID_BUTTON_SPACE                 32785
#define ID_BTN_GRAPH_CLEAR2             32786
#define ID_BTN_GRAPH_CLEAR3             32787
#define ID_BTN_GRAPH_CLEAR4             32788
#define ID_BTN_GRAPH_CLEAR5             32789
#define ID_BTN_GRAPH_CLEAR6             32790
#define ID_BTN_GRAPH_CLEAR7             32791
#define ID_BTN_GRAPH_CLEAR8             32792
#define ID_VIEW_LIMIT                   32793
#define ID_VIEW_STATUS                  32794
#define ID_CHECK3                       32795
#define ID_BUTTON_CSVOUT                32796
#define ID_BUTTON_CAPTURE               32797
#define ID_BUTTON_PRINTOUT              32798
#define ID_BUTTON2                      32799
#define ID_BUTTON_FILE_OPEN             32800
#define ID_BUTTON_FILE_SAVE             32801

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        321
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
