//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// OperationTimeLine.rc で使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_DIALOG_FILTER               101
#define IDD_DIALOG_FILTER_EQ            103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_OperationTimeLiTYPE         130
#define ID_WINDOW_MANAGER               131
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define IDR_POPUP_EDIT1                 201
#define IDR_POPUP_TIMELINE              201
#define IDR_PASSSTATUS                  202
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDS_ERROR_EVENT_NONE            307
#define IDS_ERROR_EVENT_NONE2           308
#define IDS_ERROR_EVENT_DELETE          308
#define IDD_DIALOG_TIMELINE             310
#define IDI_ICON_FORWARD                312
#define IDI_ICON_NEXT                   313
#define IDI_ICON_TIMELINE               314
#define IDD_DIALOG_EVENTMODE            317
#define IDD_DIALOG_SELECTFORECAST       318
#define IDD_DIALOG_UPDATEOPEND          319
#define IDD_DIALOG_EVENTADD             320
#define IDI_ICON_HISTORY                320
#define IDD_DIALOG_EVENTUPDATE          321
#define IDD_DIALOG_EVENTDEL             322
#define IDD_DIALOG_OPTIONANT            323
#define IDI_ICON_STATUS                 323
#define IDD_DIALOG_EQSYSTEM             324
#define IDD_TAB_BLOCK                   325
#define IDD_TAB_ANTENNA                 326
#define IDD_DIALOG_MASTERSLAVE          327
#define IDD_DIALOG_OPEPROP              328
#define IDD_DLG_CIDSEL                  358
#define IDI_ICON_HELP                   377
#define IDI_ICON_MUTE                   378
#define IDI_ICON_SOUND                  379
#define IDI_ICON_SNAP                   380
#define IDR_PASSSTATUS1                 381
#define IDR_MENU_HCOPY                  399
#define IDR_PASSSTATUS_MON_UT           400
#define IDD_DLG_MON_UT                  439
#define IDC_STATIC_CURRENTUTC           1000
#define IDC_STATIC_TIMESCALE            1004
#define IDC_COMBO_TIMESCALE             1005
#define IDC_BUTTON_FORWARD              1006
#define IDC_BUTTON_NEXT                 1007
#define IDC_CHECK_AUTOSCROL             1008
#define IDC_STATIC_NEXTPASS             1009
#define IDC_STATIC_CURRENTTIME          1010
#define IDC_EDIT1                       1011
#define IDC_EDIT_PROPEVENTSUNSET        1011
#define IDC_STATIC_TIMELINE             1012
#define IDC_STATIC_NOTES                1013
#define IDC_STATIC_TIMELINEHEADER       1014
#define IDC_BUTTON_PLANLIST             1015
#define IDC_EDIT_PROPEVENTSUNRISE       1015
#define IDC_BUTTON_FORECAST             1016
#define IDC_BUTTON_OPESTOP              1017
#define IDC_BUTTON_UPLNK                1018
#define IDC_BUTTON_UPLNKADD             1019
#define IDC_BUTTON_UPLNKUPDATE          1020
#define IDC_CHECK_LEGEND1               1021
#define IDC_CHECK_LEGEND2               1022
#define IDC_CHECK_LEGEND3               1023
#define IDC_CHECK_LEGEND4               1024
#define IDC_CHECK_LEGEND5               1025
#define IDC_CHECK_LEGEND6               1026
#define IDC_CHECK_LEGEND7               1027
#define IDC_CHECK_LEGEND8               1028
#define IDC_CHECK_LEGEND9               1029
#define IDC_CHECK_LEGEND10              1030
#define IDC_BUTTON_UPLNKDEL             1030
#define IDC_STATIC_PLANINFO             1031
#define IDC_STATIC_SPACE                1032
#define IDC_STATIC_SPACEVAL             1033
#define IDC_STATIC_PLANID               1034
#define IDC_STATIC_PLANIDVAL            1035
#define IDC_STATIC_FORECAST             1036
#define IDC_STATIC_FORECASTVAL          1037
#define IDC_STATIC_OPESTATUS            1038
#define IDC_STATIC_OPESTATUSVAL         1039
#define IDC_STATIC_OPESTART             1040
#define IDC_STATIC_OPESTARTVAL          1041
#define IDC_STATIC_OPESTOP              1042
#define IDC_STATIC_OPESSTOPVAL          1043
#define IDC_STATIC_OPESTARTUNTIL        1044
#define IDC_STATIC_OPESTARTUNTILVAL     1045
#define IDC_STATIC_OPESTOPUNTIL         1046
#define IDC_STATIC_OPESTOPUNTILVAL      1047
#define IDC_STATIC_UPLNKSTARTUNTIL      1048
#define IDC_STATIC_UPLNKSTARTUNTILVAL   1049
#define IDC_STATIC_UPLNKSTOPUNTIL       1050
#define IDC_STATIC_UPLNKSTOPUNTILVAL    1051
#define IDC_STATIC_RNGSTARTUNTIL        1052
#define IDC_STATIC_RNGSTARTUNTILVAL     1053
#define IDC_STATIC_RNGSTOPUNTIL         1054
#define IDC_STATIC_RNGSTOPUNTILVAL      1055
#define IDC_STATIC_CMDSTARTUNTIL        1056
#define IDC_STATIC_CMDSTARTUNTILVAL     1057
#define IDC_STATIC_CMDSTOPUNTIL         1058
#define IDC_STATIC_CMDSTOPUNTILVAL      1059
#define IDC_STATIC_UPLNKINFO            1060
#define IDC_STATIC_UPLNK_RUN            1061
#define IDC_STATIC_UPLNKEVENT           1062
#define IDC_STATIC_UPLNKSTART           1063
#define IDC_STATIC_UPLNKSTARTVAL        1064
#define IDC_STATIC_UPLNKRUNVAL          1065
#define IDC_STATIC_UPLNKEVENTVAL        1066
#define IDC_STATIC_UPLNKNO              1067
#define IDC_COMBO_UPLNKNO               1068
#define IDC_STATIC_UPLNKSTOP            1069
#define IDC_STATIC_UPLNKSTOPVAL         1070
#define IDC_STATIC_CMDINFO              1071
#define IDC_STATIC_CMD_RUN              1072
#define IDC_STATIC_CMDEVENT             1073
#define IDC_BUTTON_CMD                  1074
#define IDC_STATIC_CMDRUNVAL            1075
#define IDC_STATIC_CMDEVENTVAL          1076
#define IDC_STATIC_CMDNO                1077
#define IDC_COMBO_CMDNO                 1078
#define IDC_STATIC_CMDSTART             1079
#define IDC_STATIC_CMDSTARTVAL          1080
#define IDC_BUTTON_CMDADD               1081
#define IDC_BUTTON_CMDUPDATE            1082
#define IDC_BUTTON_CMDDEL               1083
#define IDC_STATIC_CMDSTOP              1084
#define IDC_STATIC_CMDSTOPVAL           1085
#define IDC_STATIC_RNGINFO              1086
#define IDC_STATIC_RNG_RUN              1087
#define IDC_STATIC_RNGEVENT             1088
#define IDC_BUTTON_RNG                  1089
#define IDC_STATIC_RNGRUNVAL            1090
#define IDC_STATIC_RNGEVENTVAL          1091
#define IDC_STATIC_RNGNO                1092
#define IDC_COMBO_RNGNO                 1093
#define IDC_STATIC_RNGSTART             1094
#define IDC_STATIC_RNGSTARTVAL          1095
#define IDC_BUTTON_RNGADD               1096
#define IDC_BUTTON_RNGUPDATE            1097
#define IDC_BUTTON_RNGDEL               1098
#define IDC_STATIC_RNGSTOP              1099
#define IDC_STATIC_RNGSTOPVAL           1100
#define IDC_STATIC_OPEOPTION            1101
#define IDC_STATIC_OPEOPINIT            1102
#define IDC_STATIC_OPEOPINITVAL         1103
#define IDC_STATIC_OPEOPSEND            1104
#define IDC_STATIC_OPEOPSENDVAL         1105
#define IDC_STATIC_OPEOPRECV            1106
#define IDC_STATIC_OPEOPRECVVAL         1107
#define IDC_STATIC_OPEOPSENDOUT         1108
#define IDC_STATIC_OPEOPSENDOUTVAL      1109
#define IDC_STATIC_OPEOPLNA             1110
#define IDC_STATIC_OPEOPLNAVAL          1111
#define IDC_STATIC_OPEOPANTWAIT         1112
#define IDC_STATIC_OPEOPANTWAITVAL      1113
#define IDC_STATIC_OPEOPANT             1114
#define IDC_STATIC_OPEOPANTVAL          1115
#define IDC_BUTTON_FORECAST2            1116
#define IDC_BUTTON_ANT                  1116
#define IDC_STATIC_READINESS            1117
#define IDC_STATIC_READAGC              1118
#define IDC_STATIC_READAGCVAL           1119
#define IDC_STATIC_READRNG              1120
#define IDC_STATIC_READRNGVAL           1121
#define IDC_STATIC_READTLM              1122
#define IDC_STATIC_READTLMVAL           1123
#define IDC_STATIC_READCMD              1124
#define IDC_STATIC_READCMDVAL           1125
#define IDC_STATIC_MASTERSLAVE          1126
#define IDC_EDIT_PROPMARGINULON         1127
#define IDC_STATIC_PROPERTY             1128
#define IDC_EDIT_EIRP                   1129
#define IDC_STATIC_CURRENTTIME2         1129
#define IDC_STATIC_MSVAL                1130
#define IDC_EDIT_EXPECT                 1131
#define IDC_STATIC_PROPEVENT            1132
#define IDC_STATIC_PROPEVENTAUTO        1133
#define IDC_COMBO_PROPEVENTAUTOVAL      1134
#define IDC_STATIC_STLM                 1135
#define IDC_EDIT_RECLEVELVAL            1136
#define IDC_EDIT_RECLEVELVALS           1136
#define IDC_STATIC_STLMRUN              1137
#define IDC_EDIT_TLM                    1138
#define IDC_STATIC_STLMRUNVAL           1139
#define IDC_EDIT_CMD                    1140
#define IDC_STATIC_STLMSTART            1141
#define IDC_STATIC_STLMSTARTVAL         1142
#define IDC_STATIC_STLMSTOP             1143
#define IDC_STATIC_STLMSTOPVAL          1144
#define IDC_STATIC_PROPEVENTSUNSET      1145
#define IDC_STATIC_PROPMARGIN           1146
#define IDC_STATIC_XTLM                 1147
#define IDC_STATIC_XTLMRUN              1148
#define IDC_STATIC_XTLMRUNVAL           1149
#define IDC_STATIC_XTLMSTART            1150
#define IDC_STATIC_XTLMSTARTVAL         1151
#define IDC_STATIC_XTLMSTOP             1152
#define IDC_STATIC_XTLMSTOPVAL          1153
#define IDC_STATIC_KATLM                1154
#define IDC_STATIC_KATLMRUN             1155
#define IDC_STATIC_KATLMRUNVAL          1156
#define IDC_STATIC_KATLMSTART           1157
#define IDC_STATIC_KATLMSTARTVAL        1158
#define IDC_STATIC_KATLMSTOP            1159
#define IDC_STATIC_KATLMSTOPVAL         1160
#define IDC_BUTTON_MASTERSLAVE          1161
#define IDC_BUTTON_PROPSET              1162
#define IDC_BUTTON_PROPRESET            1163
#define IDC_STATIC_PROPEVENTDEG         1164
#define IDC_STATIC_PROPMARGINDEG        1165
#define IDC_STATIC_PROPEVENTSUNRISE     1166
#define IDC_STATIC_PROPMARGINULON       1167
#define IDC_STATIC_PROPMARGINULOFF      1168
#define IDC_EDIT_PROPMARGINULOFF        1169
#define IDC_STATIC_PROPMARGINDL         1170
#define IDC_EDIT_PROPMARGINDL           1171
#define IDC_STATIC_PROPUL               1172
#define IDC_STATIC_PROPULOFFSET         1173
#define IDC_STATIC_PROPULCMD            1174
#define IDC_EDIT_PROPULCMD              1175
#define IDC_STATIC_PROPULRNG            1176
#define IDC_EDIT_PROPULRNG              1177
#define IDC_STATIC_DEFCID               1178
#define IDC_STATIC_PROPCID              1179
#define IDC_BUTTON_PROPCID              1180
#define IDC_STATIC_PROPSPACE            1181
#define IDC_STATIC_PROPSPACETEXT        1182
#define IDC_COMBO_PROPSPACEVAL          1183
#define IDC_BUTTON_PROPINIT             1183
#define IDC_STATIC_INITIALIZE           1184
#define IDC_EDIT_RECLEVELVALX           1184
#define IDC_STATIC_EVENT                1185
#define IDC_RADIO1                      1186
#define IDC_COMBO_LEAPYEAR              1187
#define IDC_RADIO2                      1188
#define IDC_LIST1                       1189
#define IDC_COMBO_LEAPSEC               1190
#define IDC_STATIC_TEXT                 1191
#define IDC_RADIO3                      1192
#define IDC_COMBO_RECLEVEL              1193
#define IDC_STATIC_BTIME                1194
#define IDC_STATIC_BEND                 1195
#define IDC_STATIC_BSTART               1196
#define IDC_FAPANEL1                    1197
#define IDC_LIST_WAY                    1198
#define IDC_CHECK_TLM                   1199
#define IDC_CHECK_CMD                   1200
#define IDC_STATIC_INIT                 1201
#define IDC_EDIT_PROPEVENTAUTOVAL       1202
#define IDC_EDIT_PROPSPACEVAL           1203
#define IDC_RNG_TYPE                    1204
#define IDC_CIDSEL_SATELLITE_CMB        1205
#define IDC_COMBO1                      1205
#define IDC_RNGTYPECMB                  1205
#define IDC_CIDSEL_CID_CMB              1206
#define IDC_STATIC_RCVLEVEL_X           1206
#define IDC_CIDSEL_TLMBR_S_CMB          1207
#define IDC_STATIC_RCVLEVEL_S           1207
#define IDC_CIDSEL_TLMBR_X_CMB          1208
#define IDC_CIDSEL_TLMBR_KA_CMB         1209
#define IDC_CIDSEL_CLB_S_CMB            1210
#define IDC_CIDSEL_CLB_X_CMB            1211
#define IDC_CIDSEL_CLB_KA_CMB           1212
#define IDC_CIDSEL_RPRM_SR_CMB          1213
#define IDC_CIDSEL_MMTD_S_CMB           1216
#define IDC_CIDSEL_MMTD_X_CMB           1217
#define IDC_CIDSEL_ANTAT_MIG_CMB        1218
#define IDC_CIDSEL_CMDBR_S_CMB          1219
#define IDC_CIDSEL_CMDBR_X_CMB          1220
#define IDC_CIDSEL_TPWR_PWR_CMB         1221
#define IDC_CIDSEL_TLMBR_HX_CMB         1222
#define IDC_CIDSEL_UPLNK_SHP_CMB        1223
#define IDC_CIDSEL_ANTSTDORIENTED_CMB   1224
#define IDC_CIDSEL_ANTSTDPOSORIENTED_CMB 1225
#define IDC_CIDSEL_CMDMDL_MDL_CMB       1226
#define IDC_CIDSEL_CMDSUBFREQ_FREQ_CMB  1227
#define IDC_CIDSEL_TDOP_CMP_CMB         1228
#define IDC_CIDSEL_SATELLITE_STATIC     2150
#define IDC_CIDSEL_CID_STATIC           2151
#define IDC_CIDSEL_TLMBR_STATIC         2153
#define IDC_CIDSEL_TLMBR_S_STATIC       2155
#define IDC_CIDSEL_TLMBR_X_STATIC       2157
#define IDC_CIDSEL_TLMBR_HX_STATIC      2158
#define IDC_CIDSEL_TLMBR_KA_STATIC      2159
#define IDC_CIDSEL_CLB_STATIC           2167
#define IDC_CIDSEL_CLB_S_STATIC         2169
#define IDC_CIDSEL_CLB_X_STATIC         2171
#define IDC_CIDSEL_CLB_KA_STATIC        2173
#define IDC_CIDSEL_RPRM_STATIC          2181
#define IDC_CIDSEL_RPRM_SR_STATIC       2183
#define IDC_CIDSEL_MMTD_STATIC          2193
#define IDC_CIDSEL_MMTD_S_STATIC        2195
#define IDC_CIDSEL_MMTD_X_STATIC        2197
#define IDC_CIDSEL_ANTAT_STATIC         2199
#define IDC_CIDSEL_ANTSTDORIENTED_STATIC 2200
#define IDC_CIDSEL_ANTAT_MIG_STATIC     2201
#define IDC_CIDSEL_ANTSTDORIENTED_UMU_STATIC 2202
#define IDC_CIDSEL_CMDBR_STATIC         2203
#define IDC_CIDSEL_CMDBR_S_STATIC       2204
#define IDC_CIDSEL_ANTSTDPOSORIENTED_STATIC 2205
#define IDC_CIDSEL_CMDBR_X_STATIC       2206
#define IDC_CIDSEL_ANTSTDPOSORIENTED_UMU_STATIC 2207
#define IDC_CIDSEL_TPWR_STATIC          2212
#define IDC_CIDSEL_TPWR_PWR_STATIC      2214
#define IDC_CIDSEL_UPLNK_STATIC         2218
#define IDC_CIDSEL_UPLNK_SHP_STATIC     2220
#define IDC_CIDSEL_CMDMDL_STATIC        2225
#define IDC_CIDSEL_CMDMDL_MDL_STATIC    2226
#define IDC_CIDSEL_CMDSUBFREQ_STATIC    2228
#define IDC_CIDSEL_CMDSUBFREQ_FREQ_STATIC 2229
#define IDC_CIDSEL_TDOP_STATIC          2231
#define IDC_CIDSEL_TDOP_CMP_STATIC      2232
#define IDC_EQSYSTEM_LOC                2252
#define IDC_MON_UT_LIST                 2606
#define IDC_MON_UT_WRITE_BTN            2607
#define IDC_MON_UT_READ_BTN             2608
#define IDC_MON_UT_RENEW_BTN            2609
#define IDC_MON_UT_FNAME_EDIT           2610
#define IDC_BUTTON_SELECTALL            3000
#define IDC_BUTTON_EXEC                 3001
#define IDC_STATIC_STATION              3002
#define IDC_STATIC_SENDEQ               3003
#define IDC_STATIC_STATUS               3004
#define IDC_STATIC_MESSAGE              3005
#define IDC_EDIT_MESSAGE                3006
#define IDC_CHECK_STATION1              3011
#define IDC_CHECK_STATION2              3012
#define IDC_CHECK_STATION3              3013
#define IDC_CHECK_STATION4              3014
#define IDC_CHECK_STATUS1               3021
#define IDC_CHECK_STATUS2               3022
#define IDC_CHECK_STATUS3               3023
#define IDC_CHECK_STATUS4               3024
#define IDC_CHECK_STATUS5               3025
#define IDC_CHECK_STATUS6               3026
#define IDC_STATIC_IMPORT               3030
#define IDC_CHECK_IMSTATUS1             3031
#define IDC_CHECK_IMSTATUS2             3032
#define IDC_CHECK_IMSTATUS3             3033
#define IDC_DATETIMEPICKER_SDATE        8026
#define IDC_DATETIMEPICKER_STIME        8027
#define IDC_DATETIMEPICKER_EDATE        8028
#define IDC_DATETIMEPICKER_ETIME        8029
#define IDC_BUTTON_SENDER               8031
#define ID_MP_PLANLIST                  32771
#define ID_MP_FORECASTLIST              32772
#define ID_MS_PLANNING                  32773
#define ID_MS_OPETIMELINE               32774
#define ID_MS_ORBITDATA                 32775
#define ID_MS_SESSIONSTATE4             32776
#define ID_TIMEOFFSET_SET               32777
#define ID_OP_STARTTIME_CHG             32778
#define ID_OP_ENDTIME_CHG               32779
#define ID_FORCED_OP_STOP               32780
#define ID_MC_CALIBDIAGNS               32781
#define ID_FILE_NER                     32782
#define ID_VIEW_PASSSTATUS              32783
#define ID_VIEW_EQUIPMENT               32784
#define ID_VIEW_EVENT                   32785
#define ID_VIEW_LIMITERROR              32786
#define ID_HCOPY_NORMAL                 32787
#define ID_HCOPY_REVERSE                32788
#define ID_32789                        32789
#define ID_MH_MANUAL                    32790
#define ID_32791                        32791
#define ID_MON_UT                       32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        330
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1208
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
